# Generated by Django 4.2.3 on 2023-08-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_server', '0002_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('project', 'name')},
        ),
    ]
