# Generated by Django 4.2.3 on 2023-09-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_server', '0003_alter_asset_name_alter_asset_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='hash',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
