# Generated by Django 4.2.3 on 2024-01-03 20:24

from django.db import migrations, models
import tf_server.models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_server', '0004_asset_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published_bundle',
            field=models.FileField(default=None, null=True, upload_to=tf_server.models._published_bundle_path),
        ),
    ]
